document.fonts.add(new FontFace('Mulish', 'url(node_modules/@beagives/bea-font/mulish.woff2)'))
document.fonts.add(new FontFace('Pangram', 'url(node_modules/@beagives/bea-font/pangram-extralight.woff2)', { weight: '200' }))
document.fonts.add(new FontFace('Pangram', 'url(node_modules/@beagives/bea-font/pangram-regular.woff2)', { weight: '400' }))
document.fonts.add(new FontFace('Pangram', 'url(node_modules/@beagives/bea-font/pangram-bold.woff2)', { weight: '700' }))
document.fonts.add(new FontFace('Pangram', 'url(node_modules/@beagives/bea-font/pangram-extrabold.woff2)', { weight: '800' }))
document.fonts.add(new FontFace('Pangram', 'url(node_modules/@beagives/bea-font/pangram-black.woff2)', { weight: '900' }))
